### ISSUE TITLE
Destroying cobblestone causes incorrect agent animation

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#87] opened 2017-09-07 19:01 UTC
Found at: https://code-dot-org.github.io/craft/
Destroying Cobblestone causes the Agent to perform an infinite "boink" animation in which the Agent faces to the left (regardless of the direction of the destroyed Cobblestone block)

1. Place a cobblestone block
2. Destroy the cobblestone block
3. Observe agent animation

[video.zip](https://github.com/code-dot-org/craft/files/1285825/video.zip)

**Comment by joshlory** [comment] 2017-09-12 22:33
Duplicate of https://github.com/code-dot-org/craft/issues/87.

**Closed by joshlory** 2017-09-12 22:33 UTC
