### ISSUE TITLE
Parity: In Minecraft Steve/Alex will be pushed into an empty space by an activated piston.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#239] opened 2017-10-06 20:42 UTC
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/10

When a player activates a piston onto Steve/Alex the piston arm will push the player into any empty space in Minecraft. When the next location is blocked, the piston arm will pass through Steve and Alex. In Hour of Code the Piston Arm passes through Steve and Alex no matter if there is a block in the next location. In future Hour of Codes this may cause an issue.

Repro steps:
1)	Start level 10.
2)	Apply the Code given in the video.
3)	Start the simulation.
4)	Move Steve/Alex into position.
5)	Observe the issue when the piston activates.

Actual Results:
The piston arm will pass through Steve/Alex.

Expected Results:
The piston arm will match parity of Minecraft.

Video:
[Microsoft Edge 10_6_2017 1_39_53 PM.zip](https://github.com/code-dot-org/craft/files/1363854/Microsoft.Edge.10_6_2017.1_39_53.PM.zip)

**Comment by joshlory** [comment] 2017-10-06 23:21
Duplicate of https://github.com/code-dot-org/craft/issues/117.

**Closed by joshlory** 2017-10-06 23:21 UTC
Labels: duplicate

**Comment by joshlory** [comment] 2017-10-06 23:23
Ah sorry, I re-read the bug description and I see this is for the case where there is no block preventing the player from being pushed over one grid space.

I think these have the same root cause and we'll want to track them under the same issue.

**Comment by v-jaarba** [comment] 2017-10-07 00:09
correct, this is a parity issue with Minecraft and it could lead to confusion if piston use is ever attempted by players that use both Minecraft and Minecraft hour of code.
