### ISSUE TITLE
Piston pulls Torch when deactivated in Level 12

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#276] opened 2017-10-12 20:56 UTC
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/12

After destroying the Redstone Torch at the end of the rail path, the Piston blocking the exit retracts. However, it seems to be a Sticky Piston that also pulls the torch signifying the victory block with it.

Steps:
1. Load Level 12
2. Write code for the Agent to destroy the Redstone Torch
3. Run the code
4. Observe the Sticky Piston pulling the Torch

Attachments:
![ezgif-4-1e8506a9da](https://user-images.githubusercontent.com/31709758/31518776-2d9f1b0c-af55-11e7-8622-40fe0497f78d.gif)

**Comment by joshlory** [comment] 2017-10-12 21:19
Duplicate of https://github.com/code-dot-org/craft/issues/265.

**Closed by joshlory** 2017-10-12 21:19 UTC
Labels: duplicate
