### ISSUE TITLE
Effect of Start Over button is not saved when switching levels

### ISSUE THREAD

**Issue by LB-wokuja** [code-dot-org/craft#257] opened 2017-10-11 14:37 UTC
Github link:
https://github.com/code-dot-org/craft/issues/257

Using “Start Over” button clears the workspace area to the default. User can start building the code for current level from the scratch. However it was noted that the action invoked by pressing that button is not saved properly. 
After using it the user will change the level to any other and then will return to the level on which he used “Start Over” but the progress will be reverted to the state before using “Start Over”.
Simple solution to this would be invoke “save” of the workspace shortly after hitting “Start Over”
 
Further investigation showed up. That the code on particular puzzle is being saved only when finishing the level. This means that switching the lesson (for example while working on puzzle 6 Student decides to go back to puzzle 5 to see how he solved that one) will cause the loss of already created code. 
 
Issue was observed on macOS (safari), Windows 10 (Edge, Chrome) and Surface (Edge) and iPad(Safari).
 
Repro Steps:
1.     Load any level.
2.     Finish it. This will invoke save of the workspace.
3.     Hit the “Start Over” button.
4.     Progress for the current level is cleared.
5.     Switch to different level.
6.     Return to the previous level.
 
Attachments:
[HoC_startOvermp4.zip](https://github.com/code-dot-org/craft/files/1375988/HoC_startOvermp4.zip)

**Comment by ryansloan** [comment] 2017-10-12 23:20
Won't fix - this is by design. We only save code when things are run. You can see a similar effect if you drag out blocks to edit your program but don't hit run again - returning to the puzzle will not show that changed code.

**Closed by ryansloan** 2017-10-12 23:20 UTC
Labels: external
