### ISSUE TITLE
Player cannot finish level until agent completes algorithm of moving

### ISSUE THREAD

**Issue by LB-wokuja** [code-dot-org/craft#261] opened 2017-10-11 14:51 UTC
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/3
Found also at puzzles from 4 to 10.
 
Repro Steps:
Create algorithm, that allows you to pass level, and then add a looped action of moving ( That will not collide with possibility of finishing level).
Move Steve/Alex to the torch block, before agent will finish algorithm.
Observe issue.

Attached file:
[Player cannot end level.zip](https://github.com/code-dot-org/craft/files/1376021/Player.cannot.end.level.zip)

**Comment by joshlory** [comment] 2017-10-11 15:12
Good catch!

The Player reaching the finish square should immediately end the level, even if the Agent still has commands left in the queue.  @WilliamHarmonMS it also looks like the Agent bump animation is interrupting the Player animation.

**Comment by joshlory** [comment] 2017-10-11 15:32
Possible duplicate of issue https://github.com/code-dot-org/craft/issues/209.

**Comment by WilliamHarmonMS** [comment] 2017-10-12 16:25
@joshlory it 100% looks like a bump animation is what's doing it, and I have a fix for that in PR#268.

As for redstone charge propagation.... that's a bit trickier. That shouldn't be effecting the player's animation at all? Unless something is getting tripped up in the plane refreshing? Which would be odd.

Can we confirm that the charge....

Never mind. It's the door thing. Iron doors set player animation back to idle. That's got to be it.

**Comment by joshlory** [comment] 2017-10-16 18:59
I'm going to close this as a duplicate of https://github.com/code-dot-org/craft/issues/209.  Feel free to re-open if it turns out to be a different underlying issue.

**Closed by joshlory** 2017-10-16 18:59 UTC
Labels: bug
