### ISSUE TITLE
Command "place" is redundant on map 7 which does not contain water/lava blocks

### ISSUE THREAD

**Issue by LB-wokuja** [code-dot-org/craft#259] opened 2017-10-11 14:45 UTC
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/7
 
On Level 7 command place is redundant. There is no water/lava on which listed blocks can be placed. In the result presence of the Place command is confusing on this puzzle Level, as the user may think it can be somehow used, while there is no possibility for that.
Issue was observed on macOS (safari), Windows 10 (Edge, Chrome) and Surface (Edge) and iPad(Safari).
Steps:
1.     Load Level 7.
2.     Write code so that the Agent make use of command place<block>, with every listed block type.
3.     Run the code.

Observe that Agent is not able to place any of listed blocks on Level 7. These kinds of blocks can be placed only in place of water or lava. They cannot be placed on solid block present on this level.

Attachments:
![place command](https://user-images.githubusercontent.com/20599143/31447979-975b6f30-aea3-11e7-8135-c37630545cc4.gif)

**Comment by joshlory** [comment] 2017-10-11 15:09
I think this may be intentional (to keep a consistent toolbox across levels).  Assigning to @kiki-lee to triage.  Thanks!

**Comment by kiki-lee** [comment] 2017-10-17 18:38
Thanks, Josh.  Yep, this is by design.

**Closed by kiki-lee** 2017-10-17 18:38 UTC
Labels: curriculum
