### ISSUE TITLE
Destroying Unpowered Rail does not cause it to drop to the ground

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#103] opened 2017-09-12 22:22 UTC
Found at: https://code-dot-org.github.io/craft/

Destroying an Unpowered Rail does not cause a sprite of it to drop to the ground and be picked up by the Agent.

Steps:
1. Place Unpowered Rail
2. Destroy Unpowered Rail
3. Observe item drop (or lack thereof)

Attachment:
[HoC_UnpoweredRail_DoesntDropOnDestruction.zip](https://github.com/code-dot-org/craft/files/1297617/HoC_UnpoweredRail_DoesntDropOnDestruction.zip)

**Comment by joshlory** [comment] 2017-09-12 22:30
Duplicate of https://github.com/code-dot-org/craft/issues/81?  I think we can track these both under the same issue.

**Closed** 2017-09-12 22:39 UTC
Labels: duplicate
