### ISSUE TITLE
Minecraft callout arrow not always correct

### ISSUE THREAD

**Issue by kiki-lee** [code-dot-org/craft#320] opened 2017-10-17 19:57 UTC
The arrow is correct when you call it bottom-center or left-center, but not when you call it bottom-left or left-bottom.

Bottom-Center
<img width="392" alt="screenshot 2017-10-17 12 55 34" src="https://user-images.githubusercontent.com/1633958/31686275-950f26cc-b33a-11e7-84cb-5cf05598faeb.png">

Bottom-Left
<img width="330" alt="screenshot 2017-10-17 11 06 22" src="https://user-images.githubusercontent.com/1633958/31686276-9528aaf2-b33a-11e7-9a4a-3b99220d1f86.png">

**Comment by joshlory** [comment] 2017-10-17 20:09
Thanks Kiki!  It looks like the asset is there, but the logic for bottom-left isn't correct.

**Comment by Hamms** [comment] 2017-10-19 23:49
Looks like we [pretty explicitly only support centered positions](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/style/craft/style.scss#L1173-L1198), probably because the size of the qtip tip means that positioning is going to be funky if we try to put it in the corner. I'm going to vote we close this one as "unfortunately as designed"

**Comment by ryansloan** [comment] 2017-10-27 18:24
We should adjust the positioning of the callouts to fit the arrows we have.

**Closed** 2017-10-31 00:07 UTC
Labels: doesn't meet ship bar, external
