### ISSUE TITLE
Agents are unable to turn in place on the same block

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#84] opened 2017-09-06 23:59 UTC
Found at: https://code-dot-org.github.io/craft/

In all of the Blockly IDEs in the Code Connection App, the ability to turn the Agent in place is available. However, in HoC, pressing an arrow key moves the Agent into the corresponding adjacent block. This leads to some frustrating navigation issues where the player must move away from the item (esp. those that can be walked over) so that they can correctly orient the Agent to face it and thus be able to edit it.

Steps:
1. Place any item that can be walked over (e.g. a Rail) in the game space
2. Maneuver next to item, but do not face it
3. Attempt to turn in place to face the item
4. Observe navigational issues

Attachment:
[HoC_Agent_UnableToTurnInPlace.zip](https://github.com/code-dot-org/craft/files/1283045/HoC_Agent_UnableToTurnInPlace.zip)

**Comment by Hamms** [comment] 2017-09-30 00:07
This is a product of the 2-D Craft Playground setup, not of the Agent itself; the actual player environment has the Agent controlled by Blockly blocks just like Code Connection

**Comment by joshlory** [comment] 2017-10-05 00:46
Do we need to support the Agent turning in place for the curriculum?  +cc @kiki-lee to triage.

**Comment by kiki-lee** [comment] 2017-10-05 00:55
I can't think of a level where this is yet required.  Are there plans to make this critical?

**Comment by joshlory** [comment] 2017-10-05 19:36
I completely misunderstood this bug 🙂.  The Agent has turn right / turn left commands now.  The Player can't turn in place with arrow keys, which I believe is by design.

Re-closing as fixed.  Sorry!

**Closed by joshlory** 2017-10-05 19:36 UTC
Labels: gameplay
